site_name: Mongoz
site_description: ODM with pydantic made it simple.
site_url: https://mongoz.tarsild.io

theme:
      name: "material"
      custom_dir: docs/overrides
      language: en
      palette:
            - scheme: "default"
              primary: "blue grey"
              accent: "red"
              media: "(prefers-color-scheme: light)"
              toggle:
                    icon: "material/lightbulb"
                    name: "Switch to dark mode"
            - scheme: "slate"
              media: "(prefers-color-scheme: dark)"
              primary: "blue grey"
              accent: "red"
              toggle:
                    icon: "material/lightbulb-outline"
                    name: "Switch to light mode"
      favicon: statics/images/favicon.ico
      logo: statics/images/white.png
      features:
            - search.suggest
            - search.highlight
            - content.tabs.link
            - content.code.copy

repo_name: tarsil/mongoz
repo_url: https://github.com/tarsil/mongoz
edit_uri: ""
plugins:
      - search
      - markdownextradata:
              data: data

nav:
      - Introduction: "index.md"
      - Documents: "documents.md"
      - Embedded Documents: "embedded-documents.md"
      - Fields: "fields.md"
      - Queries: "queries.md"
      - Signals: "signals.md"
      - Settings: "settings.md"
      - Registry: "registry.md"
      - Exceptions: "exceptions.md"
      - Contributing: "contributing.md"
      - Sponsorship: "sponsorship.md"
      - Release Notes: "release-notes.md"
markdown_extensions:
      - attr_list
      - toc:
              permalink: true
      - markdown.extensions.codehilite:
              guess_lang: false
      - mdx_include:
              base_path: docs
      - admonition
      - codehilite
      - extra
      - pymdownx.superfences:
              custom_fences:
                    - name: mermaid
                      class: mermaid
                      format: !!python/name:pymdownx.superfences.fence_code_format ""
      - pymdownx.emoji:
              emoji_index: !!python/name:materialx.emoji.twemoji
              emoji_generator: !!python/name:materialx.emoji.to_svg
      - pymdownx.tabbed:
              alternate_style: true
      - md_in_html

extra:
      alternate:
            - link: /
              name: English
              lang: en
