"""
Generated by 'esmerald createproject'
"""
from functools import cached_property
from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings

from mongoz import Registry


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    environment: str = EnvironmentType.PRODUCTION
    secret_key: str
    database_url: str

    @cached_property
    def db_connection(self) -> Registry:
        """
        To make sure the registry and the database connection remains the same
        all the time, always use the cached_property.
        """
        return Registry(url=self.database_url)
