#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or default to `python3`
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

set -x

# If inside a virtualenv, use it; otherwise, let uv handle env creation
if [ "$VIRTUAL_ENV" != '' ]; then
    UV="uv"
elif [ -z "$GITHUB_ACTIONS" ]; then
    # Local dev, create a new .venv if not already active
    uv venv
    . .venv/bin/activate
    UV="uv"
else
    # On CI, assume global Python and uv are pre-installed
    UV="uv"
fi

# Install the project in editable mode with extras
$UV venv
$UV pip install go-task-bin
$UV pip install hatch
$UV pip install -e ".[dev,testing]"
