---
name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install hatch
          pip install -e .
          pip install pytest-codspeed pytest-asyncio
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: pytest benchmarks/ --codspeed
