---
name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false
      - uses: "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97" # v7.0.0
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install "hatch==1.16.5"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@e736f0d2aeb36da38e9f08eca4dff7967408d154 # v4.8.2
        with:
          mode: simulation
          run: hatch run matrix.py3.13:focused benchmarks --codspeed
