---
name: Test Suite

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    services:
      mongodb:
        image: mongo:8.0.29@sha256:02a0cc7939f5ed38f30f9bc714ef5f682d49baf9350c54acf302ce833087fe8a
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mongoadmin
          MONGO_INITDB_DATABASE: mongodb
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --username root --password mongoadmin
          --authenticationDatabase admin --eval 'quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v02
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install "hatch==1.16.5"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Run linting checks
        run: |
          hatch run lint
          hatch run format-check
      - name: Run typing checks
        run: |
          hatch run typing
          hatch run typing-negative
      - name: Run tests
        env:
          DATABASE_URI: mongodb://root:mongoadmin@localhost:27017/?authSource=admin
        run: hatch run test:test
      - name: Validate documentation
        if: matrix.python-version == '3.10'
        run: hatch run docs:validate
